[
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1687118103.816239",
        "edited": {
            "user": "U027P3N2WMQ",
            "ts": "1687118129.000000"
        },
        "client_msg_id": "13a1e0aa-b976-4bec-ab9e-19577943b8ee",
        "text": "Has anyone run into the following? I think its stemmed from a code change I implemented to write to a database but not sure why it is coming out as this error\n\n```2023-06-17 22:27:22,654 - ERROR - _get_cleared_market error\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/.local\/lib\/python3.8\/site-packages\/urllib3\/connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"\/home\/ubuntu\/.local\/lib\/python3.8\/site-packages\/urllib3\/util\/connection.py\", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"\/usr\/lib\/python3.8\/socket.py\", line 918, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:```",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "reply_count": 5,
        "reply_users_count": 2,
        "latest_reply": "1687121431.963489",
        "reply_users": [
            "UBS7QANF3",
            "U027P3N2WMQ"
        ],
        "replies": [
            {
                "user": "UBS7QANF3",
                "ts": "1687118192.739919"
            },
            {
                "user": "U027P3N2WMQ",
                "ts": "1687118336.950519"
            },
            {
                "user": "U027P3N2WMQ",
                "ts": "1687119697.866189"
            },
            {
                "user": "UBS7QANF3",
                "ts": "1687119820.571039"
            },
            {
                "user": "U027P3N2WMQ",
                "ts": "1687121431.963489"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "UEVZb",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Has anyone run into the following? I think its stemmed from a code change I implemented to write to a database but not sure why it is coming out as this error\n\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "2023-06-17 22:27:22,654 - ERROR - _get_cleared_market error\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/.local\/lib\/python3.8\/site-packages\/urllib3\/connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"\/home\/ubuntu\/.local\/lib\/python3.8\/site-packages\/urllib3\/util\/connection.py\", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File \"\/usr\/lib\/python3.8\/socket.py\", line 918, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\n\nDuring handling of the above exception, another exception occurred:"
                            }
                        ],
                        "border": 0
                    }
                ]
            }
        ]
    },
    {
        "user": "UBS7QANF3",
        "type": "message",
        "ts": "1687118192.739919",
        "client_msg_id": "C6DE11C3-B0D6-439E-99A2-D54BE23FC3D8",
        "text": "What OS?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gaaf844a4a90",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/eaaf844a4a905431d83430e563b077aa.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0011-72.png",
            "first_name": "",
            "real_name": "Maurice Berk",
            "display_name": "Mo",
            "team": "T4G9NBD2M",
            "name": "maurice",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "parent_user_id": "U027P3N2WMQ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "+JH3",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "What OS?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1687118336.950519",
        "client_msg_id": "20e6a6d9-3a8b-4a37-9dd3-b39c65a9ca1f",
        "text": "Ubuntu 20.04",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "parent_user_id": "U027P3N2WMQ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "OQy",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Ubuntu 20.04"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1687119697.866189",
        "client_msg_id": "0695b9b0-3cc0-459c-8882-92cdcd86ed0c",
        "text": "Also, nothing was written to S3 during this error period so I’ve basically got a full \/tmp. Flumine doesn’t seem to have cleaned this up, can I force this somehow",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "parent_user_id": "U027P3N2WMQ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "+jYW=",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Also, nothing was written to S3 during this error period so I’ve basically got a full \/tmp. Flumine doesn’t seem to have cleaned this up, can I force this somehow"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UBS7QANF3",
        "type": "message",
        "ts": "1687119820.571039",
        "client_msg_id": "EEBABB3E-1A5D-438D-B469-760508687E2D",
        "text": "I used to have this, I had to make some changes to the dns resolver in Ubuntu. Will remind myself tomorrow and get back to you",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gaaf844a4a90",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/eaaf844a4a905431d83430e563b077aa.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0011-72.png",
            "first_name": "",
            "real_name": "Maurice Berk",
            "display_name": "Mo",
            "team": "T4G9NBD2M",
            "name": "maurice",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "parent_user_id": "U027P3N2WMQ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "yfnUq",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I used to have this, I had to make some changes to the dns resolver in Ubuntu"
                            },
                            {
                                "type": "text",
                                "text": "."
                            },
                            {
                                "type": "text",
                                "text": " Will remind myself tomorrow and get back to you"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1687121431.963489",
        "client_msg_id": "c139eae7-5050-48d1-8d5c-350e652dab02",
        "text": "Thanks, much appreciated",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1687118103.816239",
        "parent_user_id": "U027P3N2WMQ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "j+E5",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Thanks, much appreciated"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]