[
    {
        "text": "i'm not able to download historic data\nis it something related to italy?  do you know? btw also with a UK vpn does not work for me",
        "files": [
            {
                "id": "F05L0GASD5K",
                "mode": "hidden_by_limit"
            }
        ],
        "upload": false,
        "user": "U05KGFZUNAK",
        "display_as_bot": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "1+tnc",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "i'm not able to download historic data\nis it something related to italy?  do you know? btw also with a UK vpn does not work for me"
                            }
                        ]
                    }
                ]
            }
        ],
        "type": "message",
        "ts": "1691047098.055919",
        "client_msg_id": "14cd2e30-fdb2-4fe8-95ce-bd9f287d8808",
        "thread_ts": "1691047098.055919",
        "reply_count": 3,
        "reply_users_count": 3,
        "latest_reply": "1691052034.065319",
        "reply_users": [
            "U4H19D1D2",
            "U02QDJCK3NW",
            "U05KGFZUNAK"
        ],
        "replies": [
            {
                "user": "U4H19D1D2",
                "ts": "1691047766.562089"
            },
            {
                "user": "U02QDJCK3NW",
                "ts": "1691048463.582119"
            },
            {
                "user": "U05KGFZUNAK",
                "ts": "1691052034.065319"
            }
        ],
        "is_locked": false,
        "subscribed": true,
        "last_read": "1691052034.065319"
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1691047766.562089",
        "client_msg_id": "55b07e59-63aa-4eed-b65c-dc87712b548f",
        "text": "I assume even with the VPN you are logging in to an 'italian' account?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1691047098.055919",
        "parent_user_id": "U05KGFZUNAK",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "QveUa",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I assume even with the VPN you are logging in to an 'italian' account?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U02QDJCK3NW",
        "type": "message",
        "ts": "1691048463.582119",
        "client_msg_id": "114da7e4-6f77-4064-8f98-f9210fef05d3",
        "text": "Yes, I had the same problem from Spain.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "f9b3fec110b3",
            "image_72": "https:\/\/avatars.slack-edge.com\/2021-12-11\/2822937230854_f9b3fec110b36ee68469_72.jpg",
            "first_name": "Nacho",
            "real_name": "Nacho Uve",
            "display_name": "Nacho Uve",
            "team": "T4G9NBD2M",
            "name": "nachouve",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1691047098.055919",
        "parent_user_id": "U05KGFZUNAK",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "8uNMg",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Yes, I had the same problem from Spain."
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U05KGFZUNAK",
        "type": "message",
        "ts": "1691052034.065319",
        "client_msg_id": "35192cf3-6156-4b5b-bdbd-33d8def70202",
        "text": "i connect from vpn located in UK, for other websites it works (netflix for instance)",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "fe4fff56282e",
            "image_72": "https:\/\/avatars.slack-edge.com\/2023-08-02\/5700789261920_fe4fff56282eb87519ab_72.png",
            "first_name": "Riccardo",
            "real_name": "Riccardo Fresi",
            "display_name": "Riccardo Fresi",
            "team": "T4G9NBD2M",
            "name": "riccardo.fresi",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1691047098.055919",
        "parent_user_id": "U05KGFZUNAK",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "sOy3V",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "i connect from vpn located in UK, for other websites it works (netflix for instance)"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1691052156.594849",
        "client_msg_id": "77f93cd4-ccf7-472f-a940-b2efe031c44c",
        "text": "Fixed in 2.4.2",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1690822362.139579",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "EPlzj",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Fixed in 2.4.2"
                            }
                        ]
                    }
                ]
            }
        ],
        "reactions": [
            {
                "name": "slightly_smiling_face",
                "users": [
                    "U02RN7YDRQ9"
                ],
                "count": 1
            }
        ]
    },
    {
        "user": "U02RN7YDRQ9",
        "type": "message",
        "ts": "1691070867.388399",
        "client_msg_id": "6a305fb1-7259-4b44-b434-86ca654cc900",
        "text": "Speedy !",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge46f1f8b708",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e46f1f8b708a630e3191de7b2c42b1d1.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0023-72.png",
            "first_name": "edblock",
            "real_name": "edblock",
            "display_name": "foxwood",
            "team": "T4G9NBD2M",
            "name": "eanb",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1690822362.139579",
        "parent_user_id": "U02RN7YDRQ9",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "PFdKY",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Speedy !"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U0322P0CK0E",
        "type": "message",
        "ts": "1691110257.906929",
        "client_msg_id": "78a77b95-7fce-485e-825c-2bb18d17a68b",
        "text": "Hi guys, looking at my log file I see this:\n\n```2023-08-04 09:18:40:ERROR:53:OrderStream 1001 run error\nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/flumine\/streams\/orderstream.py\", line 51, in run\n    self._stream.start()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 67, in start\n    self._read_loop()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 226, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 256, in _receive_all\n    raise SocketError(\nbetfairlightweight.exceptions.SocketError: [Connect: 1002]: Connection closed by server\n2023-08-04 09:18:42:INFO:21:Starting OrderStream 1001\n2023-08-04 09:18:42:INFO:23:[Register: 1002]: orderSubscription\n2023-08-04 09:18:42:WARNING:25:[Listener: 1002]: stream already registered, replacing data\n2023-08-04 09:18:42:INFO:115:[OrderStream: 1002]: \"OrderStream\" created \n```\nDoes anyone know what this means? My guess is that my connection gets closed but the flumine opens a new one afterwards?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ab1918814707",
            "image_72": "https:\/\/avatars.slack-edge.com\/2022-07-31\/3867647231206_ab191881470773932048_72.jpg",
            "first_name": "Vincent",
            "real_name": "Vincent Lim",
            "display_name": "Guy Incognito",
            "team": "T4G9NBD2M",
            "name": "nelsonmathsspecialist",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1691110257.906929",
        "reply_count": 1,
        "reply_users_count": 1,
        "latest_reply": "1691137075.226029",
        "reply_users": [
            "U9JHLMZB4"
        ],
        "replies": [
            {
                "user": "U9JHLMZB4",
                "ts": "1691137075.226029"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "DzPS",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi guys, looking at my log file I see this:\n\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "2023-08-04 09:18:40:ERROR:53:OrderStream 1001 run error\nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/flumine\/streams\/orderstream.py\", line 51, in run\n    self._stream.start()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 67, in start\n    self._read_loop()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 226, in _read_loop\n    received_data_raw = self._receive_all()\n  File \"\/usr\/local\/lib\/python3.10\/site-packages\/betfairlightweight\/streaming\/betfairstream.py\", line 256, in _receive_all\n    raise SocketError(\nbetfairlightweight.exceptions.SocketError: [Connect: 1002]: Connection closed by server\n2023-08-04 09:18:42:INFO:21:Starting OrderStream 1001\n2023-08-04 09:18:42:INFO:23:[Register: 1002]: orderSubscription\n2023-08-04 09:18:42:WARNING:25:[Listener: 1002]: stream already registered, replacing data\n2023-08-04 09:18:42:INFO:115:[OrderStream: 1002]: \"OrderStream\" created \n"
                            }
                        ],
                        "border": 0
                    },
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "\nDoes anyone know what this means? My guess is that my connection gets closed but the flumine opens a new one afterwards?"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]