[
    {
        "user": "U053KV09FKP",
        "type": "message",
        "ts": "1706329668.047099",
        "edited": {
            "user": "U053KV09FKP",
            "ts": "1706329784.000000"
        },
        "client_msg_id": "6d92a360-ce97-438a-82be-9b3deab2e620",
        "text": "I am getting a strange error that is preventing me from logging in. It's \"Attribute error: module 'ssl' has no attribute 'wrap_socket'\"\nAny ideas what's causing this? I'm using python 3.12\nThere is also \"INVALID_SESSION_INFORMATION\" error that comes before it but I don't know which one is causing which",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge686f0ebeb0",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e686f0ebeb0b76b2f1e9e3cd9758e4eb.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0018-72.png",
            "first_name": "Shado",
            "real_name": "Shado",
            "display_name": "Adrian",
            "team": "T4G9NBD2M",
            "name": "dualitynonduality_171",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1706329668.047099",
        "reply_count": 2,
        "reply_users_count": 2,
        "latest_reply": "1706413334.580689",
        "reply_users": [
            "U016TGY3676",
            "U053KV09FKP"
        ],
        "replies": [
            {
                "user": "U016TGY3676",
                "ts": "1706354950.347449"
            },
            {
                "user": "U053KV09FKP",
                "ts": "1706413334.580689"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "G\/SAJ",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I am getting a strange error that is preventing me from logging in. It's \"Attribute error: module 'ssl' has no attribute 'wrap_socket'\"\nAny ideas what's causing this? I'm using python 3.12\nThere is also \"INVALID_SESSION_INFORMATION\" error that comes before it but I don't know which one is causing which"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]